export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "home-caregiver",
    type: "Full time",
    location: "Remote",
    companyName: "two-years",
    companyUrl: "male",
    skills: ["HHA", "CNA"],
    link: "shorturl.at/kstx2",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    type: "Part time",
    location: "Office",
    companyName: "Yahoo",
    companyUrl: "Yahoo.com",
    skills: ["Angular", "Node.js"],
    link: "https://yahoo.com/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Mobile dev",
    type: "Contract",
    location: "Remote",
    companyName: "Facebook",
    companyUrl: "https://facebook.com",
    skills: ["flutter"],
    link: "https://facebook.com/careers",
  },
];
